WITH latest AS (
    SELECT ri.RES_ID, sc.CODE,
           ROW_NUMBER() OVER (PARTITION BY ri.RES_ID
                              ORDER BY ri.UPDATED_AT DESC) AS rn
    FROM dbo.RESERVATION_ITEM ri
    JOIN dbo.STATUS_CODE sc ON sc.STATUS_ID = ri.STATUS_ID
), tc AS (
    SELECT t.RES_ID, COUNT(*) AS TRAVELER_COUNT
    FROM dbo.TRAVELER t
    GROUP BY t.RES_ID
)
SELECT r.RES_ID,
       r.START_DATE,
       l.CODE AS LATEST_STATUS,
       ISNULL(tc.TRAVELER_COUNT, 0) AS TRAVELER_COUNT
FROM dbo.RESERVATION r
LEFT JOIN latest l ON l.RES_ID = r.RES_ID AND l.rn = 1
LEFT JOIN tc ON tc.RES_ID = r.RES_ID
WHERE r.START_DATE >= '2025-01-01' AND r.START_DATE < '2026-01-01'
