SELECT r.RES_ID,
       r.START_DATE,
       (SELECT TOP 1 sc.CODE
        FROM dbo.RESERVATION_ITEM ri
        JOIN dbo.STATUS_CODE sc ON sc.STATUS_ID = ri.STATUS_ID
        WHERE ri.RES_ID = r.RES_ID
        ORDER BY ri.UPDATED_AT DESC) AS LATEST_STATUS,
       (SELECT COUNT(*) FROM dbo.TRAVELER t
        WHERE t.RES_ID = r.RES_ID) AS TRAVELER_COUNT
FROM dbo.RESERVATION r
WHERE YEAR(r.START_DATE) = 2025
