IF DB_ID('FleetDB') IS NULL CREATE DATABASE FleetDB;
GO
USE FleetDB;
GO
IF OBJECT_ID('dbo.RESERVATION_ITEM') IS NOT NULL DROP TABLE dbo.RESERVATION_ITEM;
IF OBJECT_ID('dbo.TRAVELER') IS NOT NULL DROP TABLE dbo.TRAVELER;
IF OBJECT_ID('dbo.RESERVATION') IS NOT NULL DROP TABLE dbo.RESERVATION;
IF OBJECT_ID('dbo.STATUS_CODE') IS NOT NULL DROP TABLE dbo.STATUS_CODE;
GO
CREATE TABLE dbo.STATUS_CODE (
    STATUS_ID   INT          NOT NULL PRIMARY KEY,
    CODE        VARCHAR(20)  NOT NULL
);
CREATE TABLE dbo.RESERVATION (
    RES_ID      INT           NOT NULL PRIMARY KEY,
    START_DATE  DATE          NOT NULL,
    CHANNEL     VARCHAR(10)   NOT NULL,
    TOTAL_DUE   DECIMAL(12,2) NOT NULL
);
CREATE TABLE dbo.RESERVATION_ITEM (
    ITEM_ID     INT          NOT NULL PRIMARY KEY,
    RES_ID      INT          NOT NULL,
    STATUS_ID   INT          NOT NULL,
    UPDATED_AT  DATETIME2(0) NOT NULL
);
CREATE TABLE dbo.TRAVELER (
    TRAVELER_ID INT          NOT NULL PRIMARY KEY,
    RES_ID      INT          NOT NULL,
    AGE         INT          NOT NULL
);
GO
